style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/port
options:
  commits:
    filters:
      Type:
        - feat
        - impr
        - perf
        - fix
        - doc
  commit_groups:
    title_maps:
      feat: Feature
      impr: Website improvement
      perf: Performance improvement
      doc: Documentation
      fix: Bug destroyer
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
